!include assets/views/view-constants.yaml

name: 'machine-editor'
focus: 'name-text-box'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: [10, 50, 5, 5]
    state: 'component editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'editor-panel'
    type: view.types.panel
    dock: view.dock.top
    margin: [10, 50, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [10, 50, 15, 15]
    views:
      - name: 'row1'
        type: view.types.panel
        dock: view.dock.top
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            margin: [115, 0, 8, 0]
            alignment:
              vertical: view.alignments.vertical.middle

          - name: 'name-text-box'
            type: view.types.text-box
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            tab-stop: true
            enabled: true
            next: 'address-text-box'
            prev: 'description-text-editor'
            size:
              width: 32
              length: 32
            enabled: true

          - name: 'address-label'
            type: view.types.label
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'address: $'
            margin: [20, 0, 8, 0]
            alignment:
              vertical: view.alignments.middle

          - name: 'address-text-box'
            type: view.types.text-box
            dock: view.dock.left
            prev: 'name-text-box'
            next: 'color-editor'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            tab-stop: true
            enabled: true
            size:
              width: 8
              length: 8
            enabled: true
            input-filter: view.input-filters.hex

      - name: 'row2'
        type: view.types.panel
        dock: view.dock.top
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'color-label'
            type: view.types.label
            dock: view.dock.left
            value: 'color:'
            margin: [100, 0, 15, 0]
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

          - name: 'color-editor'
            type: view.types.palette-entry-editor
            dock: view.dock.top
            margin: [10, 0, 0, 0]
            colors:
              fg: ide.colors.dark-grey
              bg: ide.colors.fill-color
            sizing: view.sizing.fixed
            text-color: ide.colors.info-text
            enabled: true
            tab-stop: true
            palette-index: 4
            next: 'ic-pick-list'
            prev: 'address-text-box'

      - name: 'row3'
        type: view.types.panel
        margin: *ROW-MARGINS
        dock: view.dock.top
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'ic-label'
            type: view.types.label
            dock: view.dock.left
            value: 'circuit:'
            margin: [65, 0, 8, 0]
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

          - name: 'ic-pick-list'
            type: view.types.pick-list
            dock: view.dock.left
            source: sources.circuits
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            tab-stop: true
            enabled: true
            next: 'description-text-editor'
            prev: 'color-editor'

      - name: 'row4'
        type: view.types.panel
        dock: view.dock.top
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-label'
            type: view.types.label
            dock: view.dock.top
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'description:'
            margin: [0, 0, 5, 5]
            alignment:
              vertical: view.alignments.middle

          - name: 'description-text-editor'
            type: view.types.text-editor
            dock: view.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 10
              columns: 40
            tab-stop: true
            enabled: true
            next: 'close-button'
            prev: 'ic-pick-list'
            padding: [10, 10, 10, 10]
            border: view.border.dashed
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

  - name: 'button-panel'
    type: view.types.panel
    dock: view.dock.bottom
    margin: [10, 50, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [5, 5, 5, 5]
    views:
      - name: 'close-button'
        type: view.types.button
        width: 150
        value: 'Close'
        shortcut: 'ESC'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        enabled: true
        tab-stop: true
        border: view.border.solid
        next: 'name-text-box'
        prev: 'description-text-editor'
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue