!include assets/views/view-constants.yaml

name: 'machine-editor'
focus: 'name-text-box'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: [10, 50, 5, 5]
    state: 'component editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'editor-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.fill
      mode: view.layout.mode.flex
      direction: view.layout.direction.column
    margin: [10, 50, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [0, 0, 10, 10]
    views:
      - name: 'row1'
        type: view.types.panel
        layout:
          dock: view.layout.dock.top
          direction: view.layout.direction.row
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            alignment:
              vertical: view.alignments.vertical.middle

          - name: 'name-text-box'
            type: view.types.text-box
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            next: 'address-text-box'
            prev: 'ic-editor'
            size:
              width: 32
              length: 32
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]

          - name: 'address-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'address: $'
            alignment:
              vertical: view.alignments.middle
            margin: [20, 0, 0, 0]

          - name: 'address-text-box'
            type: view.types.text-box
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            size:
              width: 8
              length: 8
            enabled: true
            tab-stop: true
            prev: 'name-text-box'
            next: 'color-editor'
            margin: [20, 0, 0, 0]
            input-filter: view.input-filters.hex

      - name: 'row2'
        type: view.types.panel
        layout:
          dock: view.layout.dock.top
          direction: view.layout.direction.row
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'color-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            value: 'color:'
            margin: [0, 0, 0, 0]
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

          - name: 'color-editor'
            type: view.types.palette-entry-editor
            layout:
              dock: view.layout.dock.top
            margin: [20, 0, 0, 0]
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            text-color: ide.colors.info-text
            enabled: true
            tab-stop: true
            palette-index: 4
            next: 'description-text-editor'
            prev: 'address-text-box'

      - name: 'row3'
        type: view.types.panel
        layout:
          dock: view.layout.dock.fill
          direction: view.layout.direction.column
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'description:'
            alignment:
              vertical: view.alignments.middle
            margin: [0, 0, 5, 5]

          - name: 'description-text-editor'
            type: view.types.text-editor
            layout:
              dock: view.layout.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 8
              columns: 40
            next: 'ic-pick-list'
            prev: 'color-editor'
            padding: [10, 10, 5, 5]
            border: view.border.dashed
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text
            enabled: true
            tab-stop: true
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

      - name: 'row4'
        type: view.types.panel
        margin: *ROW-MARGINS
        layout:
          dock: view.layout.dock.top
          direction: view.layout.direction.row
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'ic-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            value: 'circuit:'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            margin: [0, 0, 0, 0]

          - name: 'ic-pick-list'
            type: view.types.pick-list
            layout:
              dock: view.layout.dock.left
            source: sources.circuits
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            next: 'ic-editor'
            prev: 'description-text-editor'
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]

      - name: 'row5'
        type: view.types.panel
        layout:
          dock: view.layout.dock.fill
          direction: view.layout.direction.column
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'ic-editor-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'circuit editor:'
            alignment:
              vertical: view.alignments.middle
            margin: [0, 0, 0, 10]

          - name: 'ic-editor'
            type: view.types.column-pick-list
            layout:
              dock: view.layout.dock.fill
              direction: view.layout.direction.row
            enabled: true
            tab-stop: true
            next: 'close-button'
            prev: 'ic-pick-list'
            border: view.border.solid
            colors:
              fg: ide.colors.info-text
              bg: ide.colors.fill-color
            column-colors: &COLUMN-COLORS
              fg: ide.colors.white
              bg: ide.colors.light-blue
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            headers:
              - title: 'Offset'
                colors: *COLUMN-COLORS
                width: 110
                alignment:
                  horizontal: view.alignments.horizontal.center
                  vertical: view.alignments.vertical.middle

              - title: 'Size'
                colors: *COLUMN-COLORS
                width: 80
                alignment:
                  horizontal: view.alignments.horizontal.center
                  vertical: view.alignments.vertical.middle

              - title: 'Name'
                colors: *COLUMN-COLORS
                width: 350
                alignment:
                  horizontal: view.alignments.horizontal.left
                  vertical: view.alignments.vertical.middle

              - title: 'Description'
                colors: *COLUMN-COLORS
                width: 625
                alignment:
                  horizontal: view.alignments.horizontal.left
                  vertical: view.alignments.vertical.middle

              - title: 'Value'
                colors: *COLUMN-COLORS
                width: 170
                alignment:
                  horizontal: view.alignments.horizontal.left
                  vertical: view.alignments.vertical.middle

  - name: 'button-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.bottom
      mode: view.layout.mode.flow
      direction: view.layout.direction.row
    margin: [10, 50, 15, 20]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [0, 10, 0, 0]
    views:
      - name: 'close-button'
        type: view.types.button
        value: 'Close'
        layout:
          dock: view.layout.dock.left
        border: view.border.solid
        next: 'name-text-box'
        prev: 'ic-editor'
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'ESC'
        shortcut-color: ide.colors.light-green