!include assets/views/view-constants.yaml

name: 'console'
focus: 'console-view'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    minimum-size: [0, 30]
    margin: [10, 10, 5, 5]
    state: 'console'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'console-view'
    type: view.types.console
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    caret-color: ide.colors.caret
    selection-color: ide.colors.selection
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
    enabled: true
    margin: [10, 10, 5, 5]

  - name: 'footer-panel'
    type: view.types.document-footer
    layout:
      dock: view.layout.dock.bottom
      direction: view.layout.direction.row
    minimum-size: [0, 30]
    margin: [10, 10, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color