!include assets/views/view-constants.yaml

name: 'console'
focus: 'console-view'
views:
  - name: 'header-panel'
    type: view.types.state-header
    dock: view.dock.top
    margin: [10, 50, 5, 5]
    state: 'console'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'footer-panel'
    type: view.types.document-footer
    dock: view.dock.bottom
    margin: [10, 50, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'console-view'
    type: view.types.console
    dock: view.dock.fill
    enabled: true
    caret-color: ide.colors.caret
    selection-color: ide.colors.selection
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
