!include assets/views/view-constants.yaml

name: 'console'
focus: 'console-view'
layout:
  dock: view.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.dock.top
      direction: view.layout.direction.row
    minimum-size: [0, 30]
    margin: [10, 10, 5, 5]
    state: 'console'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'console-panel'
    type: view.types.panel
    layout:
      dock: view.dock.fill
      mode: view.layout.mode.flow
      direction: view.layout.direction.column
    margin: [10, 10, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    views:
      - name: 'console-view'
        type: view.types.console
        layout:
          dock: view.dock.fill
        margin: [0, 0, 0, 0]
        caret-color: ide.colors.caret
        selection-color: ide.colors.selection
        colors:
          fg: ide.colors.text
          bg: ide.colors.fill-color
        enabled: true

  - name: 'footer-panel'
    type: view.types.document-footer
    layout:
      dock: view.dock.bottom
      direction: view.layout.direction.row
    minimum-size: [0, 30]
    margin: [10, 10, 5, 5]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color