!include assets/views/view-constants.yaml

name: 'hex-editor'
focus: 'memory-editor'
margins: &MARGINS [10, 10, 5, 5]
views:
  - name: 'header-panel'
    type: view.types.state-header
    dock: view.dock.top
    margin: *MARGINS
    state: 'memory editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
  - name: 'command-line-text-box'
    type: view.types.text-box
    dock: view.dock.top
    value: ''
    enabled: true
    margin: *MARGINS
    size:
      width: 60
      length: 255
    enabled: true
    sizing: view.sizing.parent
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
  - name: 'footer-panel'
    type: view.types.dock-panel
    dock: view.dock.bottom
    margin: *MARGINS
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    bounds: [0, 0, 0, 32]
    views:
      - name: 'temp-label'
        type: view.types.label
        dock: view.dock.left
        margin: *MARGINS
        value: 'footer place holder'
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.fill-color
  - name: 'memory-editor'
    type: view.types.memory-editor
    dock: view.dock.fill
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
    enabled: true
    margin: *MARGINS
    caret-color: ide.colors.caret
    selection-color: ide.colors.selection
    address-color: ide.colors.info-text