!include assets/views/view-constants.yaml

name: 'hex-editor'
focus: 'memory-editor'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
margins: &MARGINS [10, 10, 5, 5]
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: *MARGINS
    state: 'memory editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'command-line-text-box'
    type: view.types.text-box
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    value: ''
    size:
      width: 60
      length: 255
    enabled: true
    margin: *MARGINS
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color

  - name: 'memory-editor'
    type: view.types.memory-editor
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
    enabled: true
    margin: *MARGINS
    caret-color: ide.colors.caret
    selection-color: ide.colors.selection
    address-color: ide.colors.info-text

  - name: 'footer-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.bottom
      direction: view.layout.direction.row
    margin: *MARGINS
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    bounds: [0, 0, 0, 32]
    views:
      - name: 'temp-label'
        type: view.types.label
        dock: view.dock.left
        margin: *MARGINS
        value: 'footer place holder'
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.fill-color
