!include assets/views/view-constants.yaml

name: 'machine-list'
focus: 'pick-list'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    minimum-size: [0, 30]
    margin: [10, 50, 5, 5]
    state: 'machine list'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'pick-list'
    type: view.types.column-pick-list
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    tab-stop: true
    enabled: true
    next: 'add-button'
    prev: 'delete-button'
    margin: [10, 50, 10, 10]
    border: view.border.solid
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    column-colors: &COLUMN-COLORS
      fg: ide.colors.white
      bg: ide.colors.light-blue
    row-color: ide.colors.text
    not-found-color: ide.colors.red
    selection-color: ide.colors.white
    headers:
      - title: 'ID'
        colors: *COLUMN-COLORS
        width: 125
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Name'
        colors: *COLUMN-COLORS
        width: 525
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Address Space'
        colors: *COLUMN-COLORS
        width: 250
        type: view.column.types.value
        format: view.column.formats.hex8
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Display'
        colors: *COLUMN-COLORS
        width: 525
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle

  - name: 'button-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.bottom
      direction: view.layout.direction.row
    margin: [10, 50, 15, 20]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [0, 10, 0, 0]
    views:
      - name: 'add-button'
        type: view.types.button
        value: 'Add'
        layout:
          dock: view.layout.dock.left
        enabled: true
        tab-stop: true
        next: 'edit-button'
        prev: 'pick-list'
        minimum-size: [200, 50]
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        shortcut: 'F1'
        shortcut-color: ide.colors.light-green

      - name: 'edit-button'
        type: view.types.button
        value: 'Edit'
        margin: *BUTTON-MARGINS
        layout:
          dock: view.layout.dock.left
        enabled: true
        tab-stop: true
        next: 'delete-button'
        prev: 'add-button'
        minimum-size: [200, 50]
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        shortcut: 'RET'
        shortcut-color: ide.colors.light-green

      - name: 'delete-button'
        type: view.types.button
        layout:
          dock: view.layout.dock.left
        enabled: true
        tab-stop: true
        value: 'Delete'
        next: 'pick-list'
        prev: 'edit-button'
        minimum-size: [200, 50]
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        shortcut: 'DEL'
        shortcut-color: ide.colors.light-green