!include assets/views/view-constants.yaml

name: 'machine-editor'
views:
  - name: 'header-panel'
    type: view.types.state-header
    dock: view.dock.top
    margin: [10, 50, 5, 15]
    state: 'machine editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
  - name: 'top-panel'
    type: view.types.dock-panel
    dock: view.dock.top
    margin: [10, 50, 5, 15]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [10, 50, 15, 15]
    views:
      - name: 'row1'
        type: view.types.dock-panel
        dock: view.dock.top
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            margin: [52, 0, 0, 0]
            alignment:
              horizontal: view.alignments.horizontal.right
              vertical: view.alignments.vertical.middle
          - name: 'name-textbox'
            type: view.types.text-box
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            margin: [20, 0, 0, 0]
            size:
              width: 32
              length: 32
            enabled: true
          - name: 'address-space-label'
            type: view.types.label
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'address space: $'
            margin: [20, 0, 0, 0]
            alignment:
              vertical: view.alignments.middle
          - name: 'address-space-textbox'
            type: view.types.text-box
            dock: view.dock.left
            prev: 'name-textbox'
            next: 'display-pick-list'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            margin: [20, 0, 0, 0]
            size:
              width: 8
              length: 8
            enabled: true
            input-filter: view.input-filters.hex
      - name: 'row2'
        type: view.types.dock-panel
        margin: *ROW-MARGINS
        dock: view.dock.top
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'display-label'
            type: view.types.label
            dock: view.dock.left
            value: 'display:'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
          - name: 'display-pick-list'
            type: view.types.pick-list
            dock: view.dock.left
            source: sources.displays
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            margin: [20, 0, 0, 0]
      - name: 'row3'
        type: view.types.dock-panel
        margin: *ROW-MARGINS
        dock: view.dock.top
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-text-editor'
            type: view.types.text-editor
            dock: view.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 6
              columns: 10
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color