!include assets/views/view-constants.yaml

name: 'machine-editor'
focus: 'name-text-box'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: [10, 10, 5, 5]
    state: 'machine editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'top-panel'
    type: view.types.panel
    margin: [10, 10, 5, 5]
    layout:
      dock: view.layout.dock.fill
      mode: view.layout.mode.flex
      direction: view.layout.direction.column
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [0, 0, 10, 10]
    views:
      - name: 'row1'
        type: view.types.panel
        layout:
          dock: view.layout.dock.top
          direction: view.layout.direction.row
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            alignment:
              horizontal: view.alignments.horizontal.right
              vertical: view.alignments.vertical.middle

          - name: 'name-text-box'
            type: view.types.text-box
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            next: 'address-space-text-box'
            prev: 'map-button'
            size:
              width: 32
              length: 32
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]

          - name: 'address-space-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'address space: $'
            margin: [20, 0, 0, 0]
            alignment:
              vertical: view.alignments.middle

          - name: 'address-space-text-box'
            type: view.types.text-box
            layout:
              dock: view.layout.dock.left
            prev: 'name-text-box'
            next: 'display-pick-list'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            size:
              width: 8
              length: 8
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]
            input-filter: view.input-filters.hex

      - name: 'row2'
        type: view.types.panel
        margin: *ROW-MARGINS
        layout:
          dock: view.layout.dock.top
          direction: view.layout.direction.row
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'display-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            value: 'display:'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

          - name: 'display-pick-list'
            type: view.types.pick-list
            layout:
              dock: view.layout.dock.left
            source: sources.displays
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            next: 'description-text-editor'
            prev: 'address-space-text-box'
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]

      - name: 'row3'
        type: view.types.panel
        margin: *ROW-MARGINS
        layout:
          dock: view.layout.dock.fill
          direction: view.layout.direction.column
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'description:'
            alignment:
              vertical: view.alignments.middle
            margin: [0, 0, 5, 5]

          - name: 'description-text-editor'
            type: view.types.text-editor
            layout:
              dock: view.layout.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 6
              columns: 10
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            enabled: true
            tab-stop: true
            next: 'pick-list'
            prev: 'display-pick-list'
            padding: [10, 10, 10, 10]
            border: view.border.dashed
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text

  - name: 'pick-list'
    type: view.types.column-pick-list
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    tab-stop: true
    enabled: true
    next: 'add-button'
    prev: 'description-text-editor'
    margin: [10, 10, 5, 5]
    border: view.border.solid
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    column-colors: &COLUMN-COLORS
      fg: ide.colors.white
      bg: ide.colors.light-blue
    row-color: ide.colors.text
    not-found-color: ide.colors.red
    selection-color: ide.colors.white
    headers:
      - title: 'ID'
        colors: *COLUMN-COLORS
        width: 100
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle

      - title: 'Name'
        colors: *COLUMN-COLORS
        width: 600
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle

      - title: 'Address'
        colors: *COLUMN-COLORS
        width: 150
        alignment:
          horizontal: view.alignments.horizontal.center
          vertical: view.alignments.vertical.middle

      - title: 'Integrated Circuit'
        colors: *COLUMN-COLORS
        width: 325
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle

  - name: 'button-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.bottom
      mode: view.layout.mode.flow
      direction: view.layout.direction.row
    margin: [10, 10, 15, 20]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [0, 10, 0, 0]
    views:
      - name: 'button-left-panel'
        type: view.types.panel
        layout:
          dock: view.layout.dock.left
          mode: view.layout.mode.flex
          direction: view.layout.direction.row
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'add-button'
            type: view.types.button
            value: 'Add'
            layout:
              dock: view.layout.dock.left
            enabled: true
            tab-stop: true
            next: 'edit-button'
            prev: 'pick-list'
            border: view.border.solid
            margin: *BUTTON-MARGINS
            colors:
              fg: ide.colors.light-grey
              bg: ide.colors.light-blue
            shortcut: 'F1'
            shortcut-color: ide.colors.light-green

          - name: 'edit-button'
            type: view.types.button
            value: 'Edit'
            margin: *BUTTON-MARGINS
            layout:
              dock: view.layout.dock.left
            enabled: true
            tab-stop: true
            border: view.border.solid
            next: 'delete-button'
            prev: 'add-button'
            colors:
              fg: ide.colors.light-grey
              bg: ide.colors.light-blue
            shortcut: 'RET'
            shortcut-color: ide.colors.light-green

          - name: 'delete-button'
            type: view.types.button
            value: 'Delete'
            layout:
              dock: view.layout.dock.left
            enabled: true
            tab-stop: true
            next: 'map-button'
            prev: 'edit-button'
            border: view.border.solid
            margin: *BUTTON-MARGINS
            colors:
              fg: ide.colors.light-grey
              bg: ide.colors.light-blue
            shortcut: 'DEL'
            shortcut-color: ide.colors.light-green

      - name: 'button-right-panel'
        type: view.types.panel
        layout:
          dock: view.layout.dock.right
          mode: view.layout.mode.flex
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'map-button'
            type: view.types.button
            value: 'Map'
            enabled: true
            tab-stop: true
            next: 'name-text-box'
            prev: 'delete-button'
            layout:
              dock: view.layout.dock.left
            border: view.border.solid
            margin: *BUTTON-MARGINS
            colors:
              fg: ide.colors.light-grey
              bg: ide.colors.light-blue
            shortcut: 'F2'
            shortcut-color: ide.colors.light-green