!include assets/views/view-constants.yaml

name: 'module-editor'
views:
  - name: 'header-panel'
    type: view.types.state-header
    dock: view.dock.top
    margin: [10, 50, 5, 5]
    state: 'module editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

