!include assets/views/view-constants.yaml

name: 'palette-editor'
focus: 'palette-list-box'
views:
  - name: 'header-panel'
    type: view.types.state-header
    dock: view.dock.top
    margin: [10, 50, 5, 5]
    state: 'palette editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'left-panel'
    type: view.types.dock-panel
    dock: view.dock.left
    bounds: [0, 0, 256, 256]
    margin: [10, 10, 10, 10]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    views:
      - name: 'palette-list-box'
        type: view.types.list-box
        dock: view.dock.fill
        border: view.border.solid
        padding: [0, 0, 0, 0]
        bounds: [0, 0, 300, 256]
        enabled: true
        tab-stop: true
        next: 'editor'
        prev: 'editor'
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.fill-color
        row-color: ide.colors.text
        selection-color: ide.colors.info-text

  - name: 'right-panel'
    type: view.types.dock-panel
    dock: view.dock.fill
    margin: [10, 60, 10, 10]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    views:
      - name: 'editor'
        type: view.types.palette-editor
        dock: view.dock.fill
        margin: [0, 0, 0, 10]
        enabled: true
        tab-stop: true
        prev: 'palette-list-box'
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.fill-color