!include assets/views/view-constants.yaml

name: 'project-editor'
focus: 'name-text-box'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: [10, 50, 5, 5]
    state: 'project editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'top-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.fill
      mode: view.layout.mode.flex
      direction: view.layout.direction.column
    margin: [10, 50, 10, 10]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [0, 0, 10, 10]
    views:
      - name: 'row1'
        type: view.types.panel
        layout:
          dock: view.layout.dock.left
          direction: view.layout.direction.row
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            alignment:
              horizontal: view.alignments.horizontal.right
              vertical: view.alignments.vertical.middle

          - name: 'name-text-box'
            type: view.types.text-box
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            next: 'machine-pick-list'
            prev: 'delete-button'
            margin: [20, 0, 0, 0]
            size:
              width: 32
              length: 32
            enabled: true
            tab-stop: true

          - name: 'machine-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            value: 'machine:'
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            margin: [20, 0, 0, 0]

          - name: 'machine-pick-list'
            type: view.types.pick-list
            layout:
              dock: view.layout.dock.left
            source: sources.machines
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            next: 'description-text-editor'
            prev: 'name-text-box'
            enabled: true
            tab-stop: true
            margin: [20, 0, 0, 0]

      - name: 'row2'
        type: view.types.panel
        margin: *ROW-MARGINS
        layout:
          dock: view.layout.dock.fill
          direction: view.layout.direction.column
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-label'
            type: view.types.label
            layout:
              dock: view.layout.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'description:'
            margin: [0, 0, 5, 5]
            alignment:
              vertical: view.alignments.middle

          - name: 'description-text-editor'
            type: view.types.text-editor
            layout:
              dock: view.layout.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 6
              columns: 10
            next: 'pick-list'
            prev: 'machine-pick-list'
            padding: [10, 10, 10, 10]
            border: view.border.dashed
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            enabled: true
            tab-stop: true

  - name: 'pick-list'
    type: view.types.column-pick-list
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    tab-stop: true
    enabled: true
    next: 'add-button'
    prev: 'description-text-editor'
    margin: [10, 50, 10, 10]
    border: view.border.solid
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    column-colors: &COLUMN-COLORS
      fg: ide.colors.white
      bg: ide.colors.light-blue
    headers:
      - title: 'ID'
        colors: *COLUMN-COLORS
        width: 100
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Name'
        colors: *COLUMN-COLORS
        width: 450
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Type'
        colors: *COLUMN-COLORS
        width: 175
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Assemble'
        colors: *COLUMN-COLORS
        width: 150
        alignment:
          horizontal: view.alignments.horizontal.center
          vertical: view.alignments.vertical.middle

  - name: 'button-panel'
    type: view.types.panel
    layout:
      dock: view.layout.dock.bottom
      mode: view.layout.mode.flow
      direction: view.layout.direction.row
    margin: [10, 50, 10, 20]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [0, 10, 0, 0]
    views:
      - name: 'add-button'
        type: view.types.button
        value: 'Add'
        layout:
          dock: view.layout.dock.left
        next: 'edit-button'
        prev: 'pick-list'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'F1'
        shortcut-color: ide.colors.light-green

      - name: 'edit-button'
        type: view.types.button
        value: 'Edit'
        margin: *BUTTON-MARGINS
        layout:
          dock: view.layout.dock.left
        next: 'delete-button'
        prev: 'add-button'
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'RET'
        shortcut-color: ide.colors.light-green

      - name: 'delete-button'
        type: view.types.button
        value: 'Delete'
        layout:
          dock: view.layout.dock.left
        next: 'up-button'
        prev: 'edit-button'
        margin: *BUTTON-MARGINS
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'DEL'
        shortcut-color: ide.colors.light-green

      - name: 'up-button'
        type: view.types.button
        value: 'Up'
        layout:
          dock: view.layout.dock.left
        next: 'down-button'
        prev: 'delete-button'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'CTRL+UP ARROW'
        shortcut-color: ide.colors.light-green

      - name: 'down-button'
        type: view.types.button
        value: 'Down'
        layout:
          dock: view.layout.dock.left
        next: 'active-button'
        prev: 'up-button'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        enabled: true
        tab-stop: true
        shortcut: 'CTRL+DOWN ARROW'
        shortcut-color: ide.colors.light-green

      - name: 'active-button'
        type: view.types.button
        value: 'Active'
        layout:
          dock: view.layout.dock.left
        next: 'name-text-box'
        prev: 'down-button'
        margin: *BUTTON-MARGINS
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
        tab-stop: true
        enabled: true
        shortcut: 'CTRL+RET'
        shortcut-color: ide.colors.light-green