!include assets/views/view-constants.yaml

name: 'project-editor'
focus: 'name-text-box'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    margin: [10, 50, 5, 5]
    state: 'project editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color

  - name: 'top-panel'
    type: view.types.panel
    dock: view.dock.top
    margin: [10, 50, 5, 15]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &ROW-MARGINS [10, 50, 15, 15]
    views:
      - name: 'row1'
        type: view.types.panel
        dock: view.dock.top
        margin: *ROW-MARGINS
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'name-label'
            type: view.types.label
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'name:'
            margin: [5, 0, 8, 0]
            alignment:
              horizontal: view.alignments.horizontal.right
              vertical: view.alignments.vertical.middle

          - name: 'name-text-box'
            type: view.types.text-box
            dock: view.dock.left
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: ''
            tab-stop: true
            enabled: true
            next: 'machine-pick-list'
            prev: 'delete-button'
            margin: [5, 10, 0, 0]
            size:
              width: 32
              length: 32
            enabled: true

          - name: 'machine-label'
            type: view.types.label
            dock: view.dock.left
            value: 'machine:'
            margin: [5, 0, 8, 0]
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

          - name: 'machine-pick-list'
            type: view.types.pick-list
            dock: view.dock.left
            source: sources.machines
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            row-color: ide.colors.text
            not-found-color: ide.colors.red
            selection-color: ide.colors.white
            margin: [5, 0, 0, 0]
            tab-stop: true
            enabled: true
            next: 'description-text-editor'
            prev: 'name-text-box'

      - name: 'row2'
        type: view.types.panel
        margin: [10, 50, 0, 0]
        dock: view.dock.top
        colors:
          fg: ide.colors.info-text
          bg: ide.colors.transparent
        views:
          - name: 'description-label'
            type: view.types.label
            dock: view.dock.top
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color
            value: 'description:'
            margin: [5, 0, 5, 5]
            alignment:
              vertical: view.alignments.middle

          - name: 'description-text-editor'
            type: view.types.text-editor
            dock: view.dock.fill
            document:
              rows: 64
              columns: 80
            page-size:
              rows: 6
              columns: 10
            tab-stop: true
            enabled: true
            next: 'pick-list'
            prev: 'machine-pick-list'
            caret-color: ide.colors.caret
            selection-color: ide.colors.selection
            line-number-color: ide.colors.info-text
            colors:
              fg: ide.colors.text
              bg: ide.colors.fill-color

  - name: 'pick-list'
    type: view.types.column-pick-list
    dock: view.dock.fill
    tab-stop: true
    enabled: true
    next: 'add-button'
    prev: 'description-text-editor'
    margin: [10, 50, 0, 10]
    border: view.border.solid
    sizing: view.sizing.parent
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    column-colors: &COLUMN-COLORS
      fg: ide.colors.white
      bg: ide.colors.light-blue
    headers:
      - title: 'ID'
        colors: *COLUMN-COLORS
        width: 100
        alignment:
          horizontal: view.alignments.horizontal.center
          vertical: view.alignments.vertical.middle
      - title: 'Name'
        colors: *COLUMN-COLORS
        width: 450
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Type'
        colors: *COLUMN-COLORS
        width: 175
        alignment:
          horizontal: view.alignments.horizontal.left
          vertical: view.alignments.vertical.middle
      - title: 'Assemble'
        colors: *COLUMN-COLORS
        width: 150
        alignment:
          horizontal: view.alignments.horizontal.center
          vertical: view.alignments.vertical.middle

  - name: 'button-panel'
    type: view.types.panel
    dock: view.dock.bottom
    margin: [10, 50, 10, 0]
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.transparent
    row-margins: &BUTTON-MARGINS [5, 5, 5, 5]
    views:
      - name: 'add-button'
        type: view.types.button
        width: 200
        value: 'Add'
        shortcut: 'F1'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'edit-button'
        prev: 'pick-list'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue

      - name: 'edit-button'
        type: view.types.button
        width: 200
        value: 'Edit'
        shortcut: 'RET'
        shortcut-color: ide.colors.light-green
        margin: *BUTTON-MARGINS
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'delete-button'
        prev: 'add-button'
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue

      - name: 'delete-button'
        type: view.types.button
        width: 200
        value: 'Delete'
        shortcut: 'DEL'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'up-button'
        prev: 'edit-button'
        margin: *BUTTON-MARGINS
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue

      - name: 'up-button'
        type: view.types.button
        width: 200
        value: 'Up'
        shortcut: 'CTRL+UP ARROW'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'down-button'
        prev: 'delete-button'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue

      - name: 'down-button'
        type: view.types.button
        width: 200
        value: 'Down'
        shortcut: 'CTRL+DOWN ARROW'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'active-button'
        prev: 'up-button'
        border: view.border.solid
        margin: *BUTTON-MARGINS
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue

      - name: 'active-button'
        type: view.types.button
        width: 200
        value: 'Active'
        shortcut: 'CTRL+RET'
        shortcut-color: ide.colors.light-green
        dock: view.dock.left
        tab-stop: true
        enabled: true
        next: 'name-text-box'
        prev: 'down-button'
        margin: *BUTTON-MARGINS
        border: view.border.solid
        colors:
          fg: ide.colors.light-grey
          bg: ide.colors.light-blue
