!include assets/views/view-constants.yaml

name: 'source-editor'
focus: 'text-editor'
layout:
  dock: view.layout.dock.fill
  mode: view.layout.mode.flow
  direction: view.layout.direction.column
views:
  - name: 'header-panel'
    type: view.types.state-header
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    state: 'source editor'
    state_color: ide.colors.white
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    minimum-size: [0, 30]
    margin: [10, 50, 5, 5]

  - name: 'command-line-text-box'
    type: view.types.text-box
    layout:
      dock: view.layout.dock.top
      direction: view.layout.direction.row
    value: ''
    size:
      width: 60
      length: 255
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
    enabled: true
    margin: [10, 50, 5, 5]

  - name: 'text-editor'
    type: view.types.text-editor
    layout:
      dock: view.layout.dock.fill
      direction: view.layout.direction.row
    document:
      rows: 4096
      columns: 128
    page-size:
      rows: 25
      columns: 40
    caret-color: ide.colors.caret
    selection-color: ide.colors.selection
    line-number-color: ide.colors.info-text
    colors:
      fg: ide.colors.text
      bg: ide.colors.fill-color
    enabled: true
    tab-stop: true
    margin: [10, 50, 10, 10]
    padding: [10, 10, 10, 10]
    border: view.border.dashed

  - name: 'footer-panel'
    type: view.types.document-footer
    layout:
      dock: view.layout.dock.bottom
      direction: view.layout.direction.row
    colors:
      fg: ide.colors.info-text
      bg: ide.colors.fill-color
    margin: [10, 10, 5, 5]
